# ESLint
# http://eslint.org/

env:
  browser  : true
  node     : true
  commonjs : true
  es6      : true
  mocha    : true

extends: eslint:recommended

# globals:

parserOptions:
  ecmaVersion : 6
  sourceType  : module

rules:

  # Possible Errors
  no-extra-parens              : 1 # fixable
  no-prototype-builtins        : 1
  no-unsafe-finally            : 1
  valid-jsdoc                  : 1

  # Best Practices
  accessor-pairs               : 1
  array-callback-return        : 1
  block-scoped-var             : 1
  complexity                   : 1
  consistent-return            : 1
  curly                        : 1
  default-case                 : 1
  dot-location                 : 1
  dot-notation                 : 1
  eqeqeq                       : 1
  guard-for-in                 : 1
  no-alert                     : 1
  no-caller                    : 1
  no-div-regex                 : 1
  no-else-return               : 1
  no-empty-function            : 1
  no-eq-null                   : 1
  no-eval                      : 1
  no-extend-native             : 1
  no-extra-bind                : 1
  no-extra-label               : 1
  no-floating-decimal          : 1
  no-implicit-coercion         : 1
  no-implicit-globals          : 1
  no-implied-eval              : 1
  no-invalid-this              : 1
  no-iterator                  : 1
  no-labels                    : 1
  no-lone-blocks               : 1
  no-loop-func                 : 1
  no-magic-numbers             : 1
  no-multi-spaces              : 1 # fixable
  no-multi-str                 : 1
  no-native-reassign           : 1
  no-new                       : 1
  no-new-func                  : 1
  no-new-wrappers              : 1
  no-octal-escape              : 1
  no-param-reassign            : 1
  no-proto                     : 1
  no-return-assign             : 1
  no-script-url                : 1
  no-self-compare              : 1
  no-sequences                 : 1
  no-throw-literal             : 1
  no-unmodified-loop-condition : 1
  no-unused-expressions        : 1
  no-useless-call              : 1
  no-useless-concat            : 1
  no-useless-escape            : 1
  no-void                      : 1
  no-warning-comments          : 1
  no-with                      : 1
  radix                        : 1
  vars-on-top                  : 1
  wrap-iife                    : 1
  yoda                         : 1

  # Strict Mode
  strict                       : 1

  # Variables
  init-declarations            : 1
  no-catch-shadow              : 1
  no-label-var                 : 1
  no-restricted-globals        : 1
  no-shadow                    : 1
  no-shadow-restricted-names   : 1
  no-undef-init                : 1
  no-undefined                 : 1
  no-use-before-define         : 1

  # Node.js and CommonJS
  callback-return              : 1
  global-require               : 1
  handle-callback-err          : 1
  no-mixed-requires            : 1
  no-new-require               : 1
  no-path-concat               : 1
  no-process-env               : 1
  no-process-exit              : 1
  no-restricted-modules        : 1
  no-sync                      : 1

  # Stylistic Issues
  array-bracket-spacing        : 1 # fixable
  block-spacing                : 1 # fixable
  brace-style                  : 1
  camelcase                    : 1
  comma-spacing                : 1 # fixable
  comma-style                  : 1
  computed-property-spacing    : 1 # fixable
  consistent-this              : 1
  eol-last                     : 1 # fixable
  func-names                   : 1
  func-style                   : 1
  id-blacklist                 : 1
  id-length                    : 1
  id-match                     : 1
  indent                       : 1 # fixable
  jsx-quotes                   : 1 # fixable
  key-spacing                  : 1
  keyword-spacing              : 1 # fixable
  linebreak-style              : 1 # fixable
  lines-around-comment         : 1
  max-depth                    : 1
  max-len                      : 1
  max-nested-callbacks         : 1
  max-params                   : 1
  max-statements               : 1
  max-statements-per-line      : 1
  new-cap                      : 1
  new-parens                   : 1
  newline-after-var            : 1
  newline-before-return        : 1
  newline-per-chained-call     : 1
  no-array-constructor         : 1
  no-bitwise                   : 1
  no-continue                  : 1
  no-inline-comments           : 1
  no-lonely-if                 : 1
  no-multiple-empty-lines      : 1
  no-negated-condition         : 1
  no-nested-ternary            : 1
  no-new-object                : 1
  no-plusplus                  : 1
  no-restricted-syntax         : 1
  no-spaced-func               : 1 # fixable
  no-ternary                   : 1
  no-trailing-spaces           : 1 # fixable
  no-underscore-dangle         : 1
  no-unneeded-ternary          : 1
  no-whitespace-before-property: 1
  object-curly-spacing         : 1 # fixable
  object-property-newline      : 1
  one-var                      : 1
  one-var-declaration-per-line : 1
  operator-assignment          : 1
  operator-linebreak           : 1
  padded-blocks                : 1
  quote-props                  : 1
  quotes                       : 1 # fixable
  require-jsdoc                : 1
  semi                         : 1 # fixable
  semi-spacing                 : 1 # fixable
  sort-imports                 : 1
  sort-vars                    : 1
  space-before-blocks          : 1 # fixable
  space-before-function-paren  : 1 # fixable
  space-in-parens              : 1 # fixable
  space-infix-ops              : 1 # fixable
  space-unary-ops              : 1 # fixable
  spaced-comment               : 1 # fixable
  unicode-bom                  : 1 # fixable
  wrap-regex                   : 1

  # ECMAScript 6
  arrow-body-style             : 1
  arrow-parens                 : 1
  arrow-spacing                : 1 # fixable
  generator-star-spacing       : 1 # fixable
  no-confusing-arrow           : 1
  no-duplicate-imports         : 1
  no-restricted-imports        : 1
  no-useless-computed-key      : 1
  no-useless-constructor       : 1
  no-useless-rename            : 1
  no-var                       : 1
  object-shorthand             : 1
  prefer-arrow-callback        : 1
  prefer-const                 : 1
  prefer-reflect               : 1
  prefer-rest-params           : 1
  prefer-spread                : 1
  prefer-template              : 1
  require-yield                : 1
  template-curly-spacing       : 1 # fixable
  yield-star-spacing           : 1 # fixable

  # Recommended
  # comma-dangle
  # no-cond-assign
  # no-console
  # no-constant-condition
  # no-control-regex
  # no-debugger
  # no-dupe-args
  # no-dupe-keys
  # no-duplicate-case
  # no-empty
  # no-empty-character-class
  # no-ex-assign
  # no-extra-boolean-cast
  # no-extra-semi
  # no-func-assign
  # no-inner-declarations
  # no-invalid-regexp
  # no-irregular-whitespace
  # no-negated-in-lhs
  # no-obj-calls
  # no-regex-spaces
  # no-sparse-arrays
  # no-unexpected-multiline
  # no-unreachable
  # use-isnan
  # valid-typeof
  # no-case-declarations
  # no-empty-pattern
  # no-fallthrough
  # no-octal
  # no-redeclare
  # no-self-assign
  # no-unused-labels
  # no-delete-var
  # no-undef
  # no-unused-vars
  # no-mixed-spaces-and-tabs
  # constructor-super
  # no-class-assign
  # no-const-assign
  # no-dupe-class-members
  # no-new-symbol
  # no-this-before-super

  # Removed
  # generator-star
  # global-strict
  # no-arrow-condition
  # no-comma-dangle
  # no-empty-class
  # no-empty-label
  # no-extra-strict
  # no-reserved-keys
  # no-space-before-semi
  # no-wrap-func
  # space-after-function-name
  # space-after-keywords
  # space-before-function-parentheses
  # space-before-keywords
  # space-in-brackets
  # space-return-throw-case
  # space-unary-word-ops
  # spaced-line-comment
