# ESLint
# http://eslint.org/

env:
  browser  : true
  node     : true
  commonjs : true
  mocha    : true
  es6      : true

extends: eslint:recommended

# globals:

parserOptions:
  ecmaVersion : 6
  sourceType  : module
  # ecmaFeatures:

# rules:
  # Possible Errors
