# ESLint
# http://eslint.org/

env:
  browser  : true
  node     : true
  commonjs : true
  es6      : true
  mocha    : true

extends: eslint:all

# globals:

parserOptions:
  ecmaVersion : 6
  sourceType  : module

rules:

  # Possible Errors

  # Best Practices

  # Strict Mode

  # Variables

  # Node.js and CommonJS

  # Stylistic Issues

  # ECMAScript 6
